### ISSUE TITLE
New release to fix model_baker compatibility

### ISSUE THREAD

**Issue by gavinwahl** [voiio/django-citext#35]
The latest released django-citext is broken when model_baker is installed:

```
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```

It looks like d6acc7b99c3f is meant to fix this. Can we get a release including the fix?

Thanks

**Comment by codingjoe** [comment]
Hi again,

Good thing we have a master baker on staff. @amureki, would you?

@amureki I also don't really understand your commit. Moving the registry to the packages app loading with a try block (in case you the dependency is missing) seems a more user-friendly approach. If there was a reason not to do it, maybe we should document it?

Cheers!
Joe

**Comment by amureki** [comment]
Hey there,

this is a great observation and comments, thank you!
I honestly, do not recall any more what was the reasoning behind going this way, but I agree, using Django's registry is much better option than leaving it to the users.

I am addressing it in #38
